name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

concurrency:
  group: ${{ github.workflow }}-ci-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    outputs:
      STORE_PATH: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
    strategy:
      matrix:
        node: [22, 24, 26]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node and pnpm
        uses: pnpm/setup@v2
        with:
          runtime: node@${{ matrix.node }}
          version: 12.4.1
          install: false # We'll try fetching from cache first.

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Cache pnpm store
        uses: actions/cache@v6.1.0
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # uses cache if cache hit.

      - name: Check
        run: pnpm run check

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Upload workspace artifact
        uses: actions/upload-artifact@v7
        with:
          name: workspace-node-v${{ matrix.node }}
          path: .

  test:
    needs: build
    strategy:
      matrix:
        node: [22, 24, 26]
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace artifact
        uses: actions/download-artifact@v7
        with:
          name: workspace-node-v${{ matrix.node }}
          path: .

      - name: Cache pnpm store
        uses: actions/cache@v6.1.0
        with:
          path: ${{ needs.build.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: pnpm/setup@v2
        with:
          runtime: node@${{ matrix.node }}
          version: 12.4.1
          install: false # (its in the cache)

      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v6.1.0
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run tests
        run: pnpm run test
